version: "3"

services:
  db:
    container_name: mariadb-database
    build:
      context: ./mariadb
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./logs/mariadb:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default

  php-fpm:
    container_name: php-engine
    build:
      context: ./php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${APP_PATH}:/var/www/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - default

  nginx:
    container_name: nginx-server
    build:
      context: ./nginx
      args:
        - "php-fpm"
        - "9000"
    volumes:
      - ${APP_PATH}:/var/www/app
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "8060:80"
    depends_on:
      - php-fpm
    networks:
      - default

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - 8070:80
    networks:
      - default
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_ROOT_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    depends_on:
      - db
networks:
  default:
    driver: bridge
