version: "3.5"

services:
  
  local_db:
    container_name: local_db
    image: mariadb:v1
    build: ./dockerimage/db
    ports:
      - "3306:3306"
    volumes:
      - ./dockerimage/db/mysql:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: pass
    restart: always

  local_app:
    container_name: local_app
    image: local_app
    build: './dockerimage/app'
    ports:
      - "3000:80"
    restart: always
    networks:
      - backend
    volumes:
      - ./app:/var/www/html/

  local_pma:
    container_name: local_pma
    image: phpmyadmin/phpmyadmin
    ports:
      - 3010:80
    networks:
      - backend
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=local_db
      - PMA_USER=root
      - PMA_PASSWORD=pass
    restart: always


  # local_adminer:
  #   container_name: local_adminer
  #   image: adminer
  #   ports:
  #     - 3020:8080
  #   networks:
  #     - backend
  #   restart: always

  # local_postgres:
  #   container_name: local_postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - PGPASSWORD=adminpostgres
  #   volumes:
  #     - ./db/postgres:/var/lib/postgresql/data
  #   ports:
  #       - 5433:5433
  #   networks:
  #     - backend

networks:
  backend: